name: Build Mod JAR

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
  workflow_dispatch: # Позволяет запускать сборку вручную

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: eclipse-temurin:21-jdk # Используем JDK 21
      options: --user root
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload JAR Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Mod-JARs
          path: build/libs/*.jar
