name: Build Mod JAR

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: eclipse-temurin:21-jdk
      options: --user root
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Здесь мы устанавливаем Gradle без необходимости в gradlew
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.8

      - name: Build with Gradle
        run: gradle build   # <-- команда gradle, а не ./gradlew

      - name: Upload JAR Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Mod-JARs
          path: build/libs/*.jar
